# Generated by Django 6.0.2 on 2026-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title',
            field=models.CharField(default='Untitled recipe', max_length=100),
        ),
    ]
