# Generated by Django 6.0.2 on 2026-02-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('Ukraine', 'Ukraine'), ('Germany', 'Germany'), ('Slovakia', 'Slovakia'), ('Poland', 'Poland'), ('USA', 'USA'), ('Italy', 'Italy')], null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], null=True, verbose_name='Gender'),
        ),
    ]
