# Generated by Django 6.0.2 on 2026-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_country_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('image_url', models.CharField(blank=True, db_column='Image URL', max_length=500, null=True)),
                ('rating', models.CharField(blank=True, db_column='Rating', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('prep_time', models.CharField(blank=True, db_column='Prep Time', max_length=50, null=True)),
                ('cook_time', models.CharField(blank=True, db_column='Cook Time', max_length=50, null=True)),
                ('total_time', models.CharField(blank=True, db_column='Total Time', max_length=50, null=True)),
                ('servings', models.CharField(blank=True, db_column='Servings', max_length=50, null=True)),
                ('ingredients', models.TextField(blank=True, db_column='Ingredients', null=True)),
            ],
            options={
                'db_table': 'recipes',
                'managed': False,
            },
        ),
    ]
