# Generated by Django 6.0.2 on 2026-02-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='instructions',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='title',
        ),
    ]
